version: '3.7'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: my-postgres
    user: root
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=polls
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - ./dados_bd:/bitnami/postgresql