// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using informE.Infrastructure.Persistence;

#nullable disable

namespace informE.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718230926_AddDailyMetricsAlertsGrowth")]
    partial class AddDailyMetricsAlertsGrowth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeviceMachineTask", b =>
                {
                    b.Property<Guid>("TargetDevicesId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_devices_id");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uuid")
                        .HasColumnName("tasks_id");

                    b.HasKey("TargetDevicesId", "TasksId")
                        .HasName("pk_devices_tasks");

                    b.HasIndex("TasksId")
                        .HasDatabaseName("ix_devices_tasks_tasks_id");

                    b.ToTable("devices_tasks", (string)null);
                });

            modelBuilder.Entity("DeviceSoftware", b =>
                {
                    b.Property<Guid>("DevicesId")
                        .HasColumnType("uuid")
                        .HasColumnName("devices_id");

                    b.Property<Guid>("InstalledSoftwaresId")
                        .HasColumnType("uuid")
                        .HasColumnName("installed_softwares_id");

                    b.HasKey("DevicesId", "InstalledSoftwaresId")
                        .HasName("pk_devices_softwares");

                    b.HasIndex("InstalledSoftwaresId")
                        .HasDatabaseName("ix_devices_softwares_installed_softwares_id");

                    b.ToTable("devices_softwares", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("DeviceId", "OccurredAt")
                        .HasDatabaseName("ix_alerts_device_id_occurred_at");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentKeyHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("agent_key_hash");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset>("KeyRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("key_rotated_at");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("last_ip");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("os");

                    b.Property<string>("OsUser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("os_user");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_devices_group_id");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_hostname");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_mac_address");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.DeviceDailyMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ActiveUsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_users_count");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<float>("PeakCpuPercent")
                        .HasColumnType("real")
                        .HasColumnName("peak_cpu_percent");

                    b.Property<float>("PeakDiskPercent")
                        .HasColumnType("real")
                        .HasColumnName("peak_disk_percent");

                    b.Property<float>("PeakRamPercent")
                        .HasColumnType("real")
                        .HasColumnName("peak_ram_percent");

                    b.Property<int>("UptimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("Id")
                        .HasName("pk_device_daily_metrics");

                    b.HasIndex("DeviceId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_device_daily_metrics_device_id_date");

                    b.ToTable("device_daily_metrics", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.DeviceInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Bios")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("bios");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cpu");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("gpu");

                    b.Property<int>("RamGb")
                        .HasColumnType("integer")
                        .HasColumnName("ram_gb");

                    b.Property<string>("RamType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ram_type");

                    b.Property<int>("StorageGb")
                        .HasColumnType("integer")
                        .HasColumnName("storage_gb");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("storage_type");

                    b.HasKey("Id")
                        .HasName("pk_info_devices");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_info_devices_device_id");

                    b.ToTable("info_devices", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.EnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid?>("RedeemedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_by_device_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_enrollment_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollment_tokens_token");

                    b.ToTable("enrollment_tokens", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_name");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.MachineTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SourceScript")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_script");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.NetworkGrowthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("TotalDevices")
                        .HasColumnType("integer")
                        .HasColumnName("total_devices");

                    b.Property<int>("TotalGroups")
                        .HasColumnType("integer")
                        .HasColumnName("total_groups");

                    b.HasKey("Id")
                        .HasName("pk_network_growth_snapshots");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_network_growth_snapshots_date");

                    b.ToTable("network_growth_snapshots", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("LoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_sessions_user_id_is_active");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_softwares");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_softwares_name");

                    b.ToTable("softwares", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.TaskExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MachineTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_task_id");

                    b.Property<string>("OutputLog")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("output_log");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_task_execution_logs");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_task_execution_logs_device_id");

                    b.HasIndex("MachineTaskId")
                        .HasDatabaseName("ix_task_execution_logs_machine_task_id");

                    b.ToTable("task_execution_logs", (string)null);
                });

            modelBuilder.Entity("informE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DeviceMachineTask", b =>
                {
                    b.HasOne("informE.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("TargetDevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_tasks_devices_target_devices_id");

                    b.HasOne("informE.Domain.Entities.MachineTask", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_tasks_tasks_tasks_id");
                });

            modelBuilder.Entity("DeviceSoftware", b =>
                {
                    b.HasOne("informE.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_softwares_devices_devices_id");

                    b.HasOne("informE.Domain.Entities.Software", null)
                        .WithMany()
                        .HasForeignKey("InstalledSoftwaresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_softwares_softwares_installed_softwares_id");
                });

            modelBuilder.Entity("informE.Domain.Entities.Alert", b =>
                {
                    b.HasOne("informE.Domain.Entities.Device", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("informE.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("informE.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("informE.Domain.Entities.Device", b =>
                {
                    b.HasOne("informE.Domain.Entities.Group", "Group")
                        .WithMany("Devices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_devices_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("informE.Domain.Entities.DeviceDailyMetrics", b =>
                {
                    b.HasOne("informE.Domain.Entities.Device", "Device")
                        .WithMany("DailyMetrics")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_daily_metrics_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("informE.Domain.Entities.DeviceInfo", b =>
                {
                    b.HasOne("informE.Domain.Entities.Device", "Device")
                        .WithOne("Info")
                        .HasForeignKey("informE.Domain.Entities.DeviceInfo", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_info_devices_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("informE.Domain.Entities.Session", b =>
                {
                    b.HasOne("informE.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("informE.Domain.Entities.TaskExecutionLog", b =>
                {
                    b.HasOne("informE.Domain.Entities.Device", "Device")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_execution_logs_devices_device_id");

                    b.HasOne("informE.Domain.Entities.MachineTask", "MachineTask")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("MachineTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_execution_logs_machine_tasks_machine_task_id");

                    b.Navigation("Device");

                    b.Navigation("MachineTask");
                });

            modelBuilder.Entity("informE.Domain.Entities.Device", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("DailyMetrics");

                    b.Navigation("ExecutionLogs");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("informE.Domain.Entities.Group", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("informE.Domain.Entities.MachineTask", b =>
                {
                    b.Navigation("ExecutionLogs");
                });

            modelBuilder.Entity("informE.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
